<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bypassemailsendlimitation"
 *
 * Auto generated by Extension Builder 2020-12-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Bypass email send limitation',
    'description' => 'With this extension you can bypass the send limit if the hoster allows only a certain number of mail per SMTP session. ',
    'category' => 'misc',
    'author' => 'Clemens Gogolin',
    'author_email' => 'service@cylancer.net',
    'state' => 'beta',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.9.1',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
